### ISSUE TITLE
If code expired or is invalid, make it more obvious how to resend

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#3069]
I entered an expired code and it took me a few seconds to figure out how to resend the code:

![image.png](https://images.zenhubusercontent.com/5ca2448cb4170956617cd475/025e4154-65ea-4def-a430-7f486ca16712)

The resend button says:
"**Not in inbox or spam folder?** Resend"

How might we make this experience better?

**Comment by ryanfeeley** [comment]
Fixed https://github.com/mozilla/fxa/pull/3224

**Comment by clouserw** [comment]
Fixed in #3224.  Thanks!

**Comment by vasilicatamas** [comment]
This issue was verified on Stage [Train 1.150.2] under Windows 10 64 bit and noticed that _“Need another code? Resend”_ string is successfully displayed when creating the account but the old one _"Not in inbox or spam folder? Resend"_ still appears for sign in flow. Considering that I already filed a separate bug for this issue I am marking this one as Verified.
